momichetabg/config/routes.rb
Momichetabg::Application.routes.draw do
 
  
  get "home/index"
  get "home" => 'home#index'
  get "battles/admin" => 'battles#admin'
  get "tournaments/admin" => 'tournaments#admin'
  get "pictures/admin" => 'pictures#admin'
  get "pictures/mypictures" => 'pictures#mypictures'
  get "battles/picture_history" => 'battles#picture_history'
  get "battles/subscriptions" => 'battles#subscriptions'
  get "tournaments/show_all" => 'tournaments#show_all'

  resources :battles  
  resources :tournaments
  resources :pictures
  resources :rules

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  controller :pictures do
    post 'approve_picture' => :approve_picture
    post 'disapprove_picture' => :disapprove_picture
  end  

  controller :battles do
    post 'subscribe' => :subscribe
    post 'unsubscribe' => :unsubscribe
    post 'start_tournament' => :start_tournament
    post 'move_tournament' => :move_tournament
    post 'battle_vote' => :vote
  end

  root 'home#index'

end

momichetabg/app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	belongs_to :tournament

	after_create :set_tournament

	attr_accessible :user_id, :avatar

  has_attached_file :avatar, :styles => {:medium => "", :thumb => "100x100>"}, 
  			:default_url => "/assets/:style/missing.png", 
  			:convert_options => { :medium => "-resize 380x540^ -gravity Center -crop 380x540+0+0 +repage" }
  validates_attachment_presence :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  
  private
		def set_tournament
			t = Tournament.find_by_state(1)
			if t.start_time > Time.now
				self.tournament = t
				self.save
			end	   
		end
 
end

momichetabg/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_filter :access, :except => [:show, :new, :create, :mypictures]
  before_filter :tournament, :only => :new
  

  # GET /pictures
  # GET /pictures.json

  def index
    @pictures = Picture.where(in_battle: false)
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user = current_user

    respond_to do |format|
      if @picture.save
        format.html { redirect_to new_picture_path, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  def approve_picture
    p = Picture.find(params[:id])
    p.checked = true
    p.save

    redirect_to pictures_url
  end  

  def disapprove_picture
    p = Picture.find(params[:id])
    p.checked = false
    p.save

    redirect_to pictures_url
  end 

  def mypictures 
    @mypic = current_user.pictures.where(checked: true);
  end

  private
    def access
      unless admin?
        redirect_to new_picture_path
      end
    end

    def tournament
      if Tournament.find_by_state(1).nil?
        redirect_to root_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:user_id, :avatar, :in_battle)
    end
end

momichetabg/app/helpers/pictures_helper.rb
module PicturesHelper
end

momichetabg/app/views/pictures/_form.html.erb
<%= form_for @picture, :url => pictures_path, :html => { :multipart => true } do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

momichetabg/app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= form_for @picture, method: "post" do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

momichetabg/app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>User</th>
      <th>Tournament</th>
      <th>Checked</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
      <td><%= link_to (image_tag picture.avatar.url(:thumb)), picture %></td>
        <td>
        <% if picture.user%>
          <%= picture.user.name %>
        <% end %>
        </td>
        <td>
        <% if picture.tournament %>
          <%= picture.tournament.id %>
        <% end %>
        </td>
        <td><% if !picture.checked %>
              <%= link_to 'Одобри', approve_picture_path({id: picture.id}), id: "picture_#{picture.id}", class: "btn btn-default", method: "post", remote: false %>
            <% else %> 
              <%= link_to 'Махни', disapprove_picture_path({id: picture.id}), id: "picture_#{picture.id}", class: "btn btn-default", method: "post", remote: false %>
            <% end %>
        </td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

momichetabg/app/views/pictures/mypictures.html.erb
<div class="container">
	<% if not @mypic.nil? %>
		<% @mypic.each do |pic| %>
			<%= link_to battles_picture_history_path(id: pic.id) do %>
				<%= image_tag pic.avatar.url(:medium), class: "my_pictures" %>
			<% end %> 
		<% end %>
	<% end %>
</div>

momichetabg/app/views/pictures/new.html.erb
<center><br><h1>Записване за участие в конкурса за месец май</h1></br>
<br></br>
</center>
<h5>Прочети правилата на конкурса, прикачи твоята снимка, попълни всички полета вярно и въведи своят e-mail адрес. </h5>
<h5>Изпрати покана за приятелство във <a href='https://www.facebook.com/'>Facebook </a> на профила <a href='https://www.facebook.com/profile.php?id=100008180618516'> Момичета.бг</a>, за да можем да направим контакт с теб!</h5>


<br><h4>1. Прикачете своя снимка</h4></br>
Снимката трябва да е лично ваша, без фотографско лого, вертикална, с максимално добро качество и минимална резолюция 720х960 пиксела.</br>
Ограничението на снимките е до 5Mb.</br>
Снимки с лошо качество, със слънчеви очила, с фотографско лого, само на лице и на които не се вижда лицето, пред мръсно огледало и с по-малка резолюция от горе посочената се изтриват.</br>
</br>
<% if not current_user.nil? %>
	<%= render 'form' %>
<% else %>
	<p><u><i> Моля влесте във Вашия facebook профил </i></u></p>
<% end %>

momichetabg/app/views/pictures/picture_history.html.erb
<% if not @battles.nil? %>
	puts "test"
	<% @battles.each do |b| %>
		<% @duel = b %>
		puts b.id
		<div>
			<%= render 'battle_no' %>
		</div>
	<% end %>
<% end %>

momichetabg/app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<%= image_tag @picture.avatar.url(:medium) %>
</p>

<p>
  <strong>User:</strong>
  <% if @picture.user%>
  	<%= @picture.user.name %>
  <% end %>	
</p>
<p>
  <strong>Tournament:</strong>
  <% if @picture.tournament%>
  	<%= @picture.tournament.id %>
  <% end %>	
</p>
<p>
  <strong>Checked:</strong>
  	<%= @picture.checked %>
</p>



<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>