momichetabg/config/routes.rb
Momichetabg::Application.routes.draw do
 
  
  get "home/index"
  get "home" => 'home#index'
  get "battles/admin" => 'battles#admin'
  get "tournaments/admin" => 'tournaments#admin'
  get "pictures/admin" => 'pictures#admin'
  get "pictures/mypictures" => 'pictures#mypictures'
  get "battles/picture_history" => 'battles#picture_history'
  get "battles/subscriptions" => 'battles#subscriptions'
  get "tournaments/show_all" => 'tournaments#show_all'

  resources :battles  
  resources :tournaments
  resources :pictures
  resources :rules

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  controller :pictures do
    post 'approve_picture' => :approve_picture
    post 'disapprove_picture' => :disapprove_picture
  end  

  controller :battles do
    post 'subscribe' => :subscribe
    post 'unsubscribe' => :unsubscribe
    post 'start_tournament' => :start_tournament
    post 'move_tournament' => :move_tournament
    post 'battle_vote' => :vote
  end

  root 'home#index'

end

momichetabg/app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :pictures
  has_many :battles

  attr_accessible :winner_id, :state, :start_time, :checked
end

momichetabg/app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
  before_filter :access, :except => [:show_all]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  def show_all
    @tournaments = Tournament.where(state: 3)
  end  

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
      else
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  private
    def access
      unless admin?
        redirect_to tournaments_show_all_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:winner_id, :state, :start_time)
    end
end

momichetabg/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

momichetabg/app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :state %><br>
    <%= f.select(:state, [1,2,3]) %></p>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

momichetabg/app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

momichetabg/app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Winner</th>
      <th>State</th>
      <th>Start time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.id %></td>
        <td><%= tournament.winner_id %></td>
        <td><%= tournament.state %></td>
        <td><%= tournament.start_time %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

momichetabg/app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

momichetabg/app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Winner:</strong>
  <%= @tournament.winner_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @tournament.state %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @tournament.start_time %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>

momichetabg/app/views/tournaments/show_all.html.erb
<center>
	<% @tournaments.reverse.each do |t| %>
		<% @date = t.updated_at.to_s.split(" ")[0].gsub("-", " ").split(" ").reverse %>
		<p><b><h5>Победителка от конкурса до <%= @date.join "-" %>.</h5></b></p>
		<p><b><%= Picture.find(t.winner_id).user.name %></b></p>
    	<%= image_tag Picture.find(t.winner_id).avatar.url, class: "winner_img" %>
    	</br>
	<% end %>
</center>