momichetabg/config/routes.rb
Momichetabg::Application.routes.draw do
 
  
  get "home/index"
  get "home" => 'home#index'
  get "battles/admin" => 'battles#admin'
  get "tournaments/admin" => 'tournaments#admin'
  get "pictures/admin" => 'pictures#admin'
  get "pictures/mypictures" => 'pictures#mypictures'
  get "battles/picture_history" => 'battles#picture_history'
  get "battles/subscriptions" => 'battles#subscriptions'
  get "tournaments/show_all" => 'tournaments#show_all'

  resources :battles  
  resources :tournaments
  resources :pictures
  resources :rules

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  controller :pictures do
    post 'approve_picture' => :approve_picture
    post 'disapprove_picture' => :disapprove_picture
  end  

  controller :battles do
    post 'subscribe' => :subscribe
    post 'unsubscribe' => :unsubscribe
    post 'start_tournament' => :start_tournament
    post 'move_tournament' => :move_tournament
    post 'battle_vote' => :vote
  end

  root 'home#index'

end

momichetabg/app/models/battle.rb
class Battle < ActiveRecord::Base
	belongs_to :oponent1 , class_name: "Picture", foreign_key: "oponent1_id"
	belongs_to :oponent2 , class_name: "Picture", foreign_key: "oponent2_id"
	belongs_to :tournament
	has_many :battle_votes

	attr_accessible :oponent1_id, :oponent2_id, :oponent1_votes, :oponent2_votes
	
	def winner
		if self.oponent1_votes > self.oponent2_votes
			self.oponent1_id
		elsif self.oponent1_votes < self.oponent2_votes
			self.oponent2_id
		else	
			decide = Random.new
        	i = decide.rand(1..2)
        	self.send("oponent#{i}_id")
		end		
	end

	def next
		last_id = Battle.last.id
  		if self.tournament.state == 2
  			tournament = self.tournament
  		else 
   			tournament = Tournament.find_by_state(2)
  		end 
  
  		start_id = self.id  
  		next_id = self.id + 1
  		b = 0 
  		unless self.nil?
   			while b.class != Battle or next_id == start_id do 
    			if next_id <= last_id
     				if Battle.exists?(id: next_id)
      					if Battle.find(next_id).tournament == tournament
       						if Battle.find(next_id).finished == false
        						b = Battle.find(next_id)
       						end 
      					end
     				end 
    			else
     				b = Battle.where(finished: false).where(tournament_id: tournament.id).first
    			end
   	 			next_id+= 1
    		end
  		end 
  		b
 	end

end


class Numeric
  def percent_of(n)
    self.to_f / n.to_f * 100.0
  end
end

momichetabg/app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: [:show, :edit, :update, :destroy]
  before_filter :access, :except => [:index, :show, :subscriptions, :picture_history, :vote, :subscribe, :unsubscribe]
  
  # GET /battles
  # GET /battles.json
  def index
    @battles = Battle.all
    set_duel()
  end

  # GET /battles/1
  # GET /battles/1.json
  def show
  end

  # GET /battles/new
  def new
    @battle = Battle.new
  end

  # GET /battles/1/edit
  def edit
  end

  # POST /battles
  # POST /battles.json
  def create
    @battle = Battle.new(battle_params)

    respond_to do |format|
      if @battle.save
        format.html { redirect_to @battle, notice: 'Battle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @battle }
      else
        format.html { render action: 'new' }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /battles/1
  # PATCH/PUT /battles/1.json
  def update
    respond_to do |format|
      if @battle.update(battle_params)
        format.html { redirect_to @battle, notice: 'Battle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battles/1
  # DELETE /battles/1.json
  def destroy
    @battle.destroy
    respond_to do |format|
      format.html { redirect_to battles_url }
      format.json { head :no_content }
    end
  end

  def ready_images
    if Tournament.find_by_state(1)
      Picture.where(tournament_id: Tournament.find_by_state(1).id).where(checked: true).where(in_battle: false)

    end
  end 

  def admin
    if Tournament.find_by_state(2)
      @total_images = Picture.where(tournament_id: Tournament.find_by_state(2).id).where(checked: true).where(in_battle: true).count
    else 
       @total_images = 0 
    end
    if ready_images()
      @number_of_ready_images = ready_images().count
    else
      @number_of_ready_images = 0
    end  
  end

  def get_winners
    winners = Array.new

    Battle.where(finished: false).each do |b|
      winners << Picture.find(b.winner)
    end

    winners
  end

  def subscriptions 
    @sub = Subscription.find_all_by_user_id(current_user.id)
  end

  def unsubscribe
    s = current_user.subscriptions.find_by_battle_id(params[:battle_id])
    s.delete
    @duel = Battle.find(params[:battle_id])

    respond_to do |format|
      format.js { render action: "bookmark" }
    end
  end

  def subscribe
    unless current_user.subscriptions.map(&:battle_id).include?(params[:battle_id].to_i)
      Subscription.create(user_id: current_user.id, battle_id: params[:battle_id])
    end
    @duel = Battle.find(params[:battle_id])
    
    respond_to do |format|
      format.js { render action: "bookmark" }
    end
  end

  def picture_history
    if not Picture.find(params[:id]).nil?
      if current_user.pictures.include?(Picture.find(params[:id]))
        @battles = Battle.find_all_by_oponent1_id(params[:id]) + Battle.find_all_by_oponent2_id(params[:id])
        @battles.sort_by {|obj| obj.created_at }.reverse!
      end
      #redirect_to root_path
    end
  end

  def start_tournament
    arr = ready_images()
    t = Tournament.find_by_state(1)

    tournament_step(t,arr)
    t = Tournament.create(state: 1, start_time: Time.now.utc)

    redirect_to battles_admin_path
  end

  def move_tournament
    arr = get_winners()
    t = Tournament.find_by_state(2)

    if arr.count > 1
      tournament_step(t,arr)
    else 
      t.winner_id = get_winners().first.id
      t.state = 3
      t.save

      Battle.where(tournament_id: t.id).where(finished: false).each do |b|
        b.finished = true
        b.save
      end
    end  

    redirect_to battles_admin_path
  end  

  

  def tournament_step(tournament,pics)
    arr = pics
    t = tournament

    unless t.nil?
      Battle.where(tournament_id: t.id).where(finished: false).each do |b|
        b.finished = true
        b.save
      end

      for i in 1..(arr.count/2)
        b = Battle.new
    
        p = arr.shuffle.sample
        b.oponent1_id = p.id
        p.in_battle = true
        p.save

        arr = arr.reject { |a| a == p}
    
        p = arr.shuffle.sample
        b.oponent2_id = p.id
        p.in_battle = true
        p.save

        arr = arr.reject { |a| a == p}

        b.tournament = t
        t.state = 2
        t.save

        b.save
      end    
    end
  end

  


  def vote
    b = Battle.find(params[:battle_id])
    ip = request.remote_ip
    has_user = b.battle_votes.map(&:user).include?(current_user)
    has_ip = b.battle_votes.map(&:voter_ip).include?(ip)

    if (!current_user.nil? and !has_user and !has_ip) or (!current_user.nil? and !has_user and has_ip) or (current_user.nil? and !has_ip)
        v = BattleVote.new
        v.voter_ip = ip
        v.battle = b
        v.choice = params[:choice]
        if current_user
          v.user = current_user 
        end 
        v.save

        b = Battle.find(params[:battle_id].to_i)
        if params[:choice].to_i == 1
          b.oponent1_votes += 1
        elsif params[:choice].to_i == 2
          b.oponent2_votes += 1
        end

        b.save
    end    

    @last_duel = b
    set_duel()

    respond_to do |format|
      format.html { redirect_to battles_url }
      format.js { render action: "battle" }
    end
      

  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_battle
      @battle = Battle.find(params[:id])
    end

    def set_duel
      @ip = request.remote_ip
      if current_user
        @duel = Battle.where(finished: false).reject {|b| b.battle_votes.map(&:user).include?(current_user) }
      else
        @duel = Battle.where(finished: false).reject {|b| b.battle_votes.map(&:voter_ip).include?(@ip) }
      end  
      @duel = @duel.shuffle.sample
     
      if @duel.nil?
        if @last_duel.nil?
          @duel = Battle.where(finished: false).first
        else
          @duel = @last_duel.next
        end  
      end  

      unless @duel.nil?
        if current_user and @duel.battle_votes.map(&:user).include?(current_user)
            @choice = BattleVote.where(battle_id: @duel.id).where(user_id: current_user.id).first.choice    
        elsif !current_user and @duel.battle_votes.map(&:voter_ip).include?(@ip)
          @choice = BattleVote.where(battle_id: @duel.id).where(voter_ip: @ip).first.choice
        else
          @choice = 0 
        end 
      end  

    end  

    def access
      unless admin?
        redirect_to battles_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def battle_params
      params.require(:battle).permit(:oponent1_id, :oponent2_id, :oponent1_votes, :oponent2_votes)
    end
end

momichetabg/app/helpers/battles_helper.rb
module BattlesHelper
end

momichetabg/app/views/battles/_battle.html.erb
<% if @choice != 1 and  @ch
    oice != 2 %>
    <%= javascript_include_tag "overlay/sample.js" %>
<% end %> 
   
<div class="image-holder row" id="battle">          
    <div class="col-lg-6col-md-6 col-sm-6 left-image">
        <% if (@duel.oponent1_votes + @duel.oponent2_votes) != 0 %>
            <% per = (@duel.oponent1_votes).percent_of(@duel.oponent1_votes + @duel.oponent2_votes).round(2) %>
            <% if per >= 50 %>
                <h3 class="precentage high">
            <% else %>
                <h3 class="precentage low">
            <% end %>
            <%= per %>%
        <% else %>
            <h3 class="precentage high">
            50%
        <% end %>
        </h3>
        <%= link_to battle_vote_path({battle_id: @duel.id, choice: 1}), :method => :post, class: 'vote-photo', remote: true do %>
           
                
            <% if @choice == 2 %> 
                <div class="overlay" style="display: block; background: url(http://localhost:3000/assets/overlay.png); opacity: 0.8;"></div>
            <% else %>
                <div class="overlay"><h2>Vote!</h2></div>
            <% end %>    
            <%= image_tag Picture.find(@duel.oponent1_id).avatar.url(:medium) %>
        <% end %>
        <h4 class="girl-name"><%= Picture.find(@duel.oponent1_id).user.name %>
            <% if Picture.find(@duel.oponent1_id).user.city %>
               - <%= Picture.find(@duel.oponent1_id).user.city %>
            <% end %>
        </h4>
    </div><!-- /left -->
    <div class="col-lg-6 col-md-6 col-sm-6 right-image">
        <h3 class="precentage high">
        <% if (@duel.oponent1_votes + @duel.oponent2_votes) != 0 %>
            <% per = (@duel.oponent2_votes).percent_of(@duel.oponent1_votes + @duel.oponent2_votes).round(2) %>
            <% if per >= 50 %>
                <h3 class="precentage high">
            <% else %>
                <h3 class="precentage low">
            <% end %>
            <%= per %>%
        <% else %>
            <h3 class="precentage high">
            50%
        <% end %>    
        </h3>
        <%= link_to battle_vote_path({battle_id: @duel.id, choice: 2}), :method => :post, class: 'vote-photo', remote: true do %>
            <% if @choice == 1 %> 
                <div class="overlay" style="display: block; background: url(http://localhost:3000/assets/overlay.png); opacity: 0.8;"></div>
            <% else %>
                <div class="overlay"><h2>Vote!</h2></div>
            <% end %>
            <%= image_tag Picture.find(@duel.oponent2_id).avatar.url(:medium) %>
        <% end %>
        <h4 class="girl-name"><%= Picture.find(@duel.oponent2_id).user.name %>
            <% if Picture.find(@duel.oponent2_id).user.city %>
               - <%= Picture.find(@duel.oponent2_id).user.city %>
            <% end %>
        </h4>
    </div><!-- /right -->
    <div align="center" >
        <%= render 'bookmark' %>
    </div>
</div><!-- image-holder -->
 

momichetabg/app/views/battles/_battle_nojs.html.erb
<div class="image-holder row" id="battle">
    <div style="min-height: 620px;">          
        <div class="col-lg-6col-md-6 col-sm-6 left-image">
            <% if (@duel.oponent1_votes + @duel.oponent2_votes) != 0 %>
                <% per = (@duel.oponent1_votes).percent_of(@duel.oponent1_votes + @duel.oponent2_votes).round(2) %>
                <% if per >= 50 %>
                    <h3 class="precentage high">
                <% else %>
                    <h3 class="precentage low">
                <% end %>
                <%= per %>%
            <% else %>
                <h3 class="precentage high">
                50%
            <% end %>
            </h3>
                <div class="vote-photo">
                    <% if @choice == 2 %> 
                        <div class="overlay" style="display: block; background: url(http://localhost:3000/assets/overlay.png); opacity: 0.8;"></div>
                    <% else %>
                        <div class="overlay"><h2>Vote!</h2></div>
                    <% end %>    
                    <%= image_tag Picture.find(@duel.oponent1_id).avatar.url(:medium) %>
                </div>
            <h4 class="girl-name"><%= Picture.find(@duel.oponent1_id).user.name %>
                <% if Picture.find(@duel.oponent1_id).user.city %>
                   - <%= Picture.find(@duel.oponent1_id).user.city %>
                <% end %>
            </h4>
        </div><!-- /left -->
        <div class="col-lg-6 col-md-6 col-sm-6 right-image">
            <h3 class="precentage high">
            <% if (@duel.oponent1_votes + @duel.oponent2_votes) != 0 %>
                <% per = (@duel.oponent2_votes).percent_of(@duel.oponent1_votes + @duel.oponent2_votes).round(2) %>
                <% if per >= 50 %>
                    <h3 class="precentage high">
                <% else %>
                    <h3 class="precentage low">
                <% end %>
                <%= per %>%
            <% else %>
                <h3 class="precentage high">
                50%
            <% end %>    
            </h3>
                <div class="vote-photo">
                    <% if @choice == 1 %> 
                        <div class="overlay" style="display: block; background: url(http://localhost:3000/assets/overlay.png); opacity: 0.8;"></div>
                    <% else %>
                        <div class="overlay"><h2>Vote!</h2></div>
                    <% end %>
                    <%= image_tag Picture.find(@duel.oponent2_id).avatar.url(:medium) %>
                </div>
            <h4 class="girl-name"><%= Picture.find(@duel.oponent2_id).user.name %>
                <% if Picture.find(@duel.oponent2_id).user.city %>
                   - <%= Picture.find(@duel.oponent2_id).user.city %>
                <% end %>
            </h4>
        </div><!-- /right -->
    </div>
    <div align="center" >
        <%= render 'bookmark' %>
    </div>
</div><!-- image-holder -->
 

momichetabg/app/views/battles/_bookmark.html.erb
<div id="bookmark">
	<% if not current_user.nil? %>
		<% if current_user.subscriptions.map(&:battle_id).include?(@duel.id) %>
			<%= link_to unsubscribe_path({battle_id: @duel.id}), :method => :post, remote: true, class: "bookmark_link" do %>		
				<%= image_tag "/assets/favourites-128.png", class: "bookmark" %>	
			<% end %>
		<% else %>
			<%= link_to subscribe_path({battle_id: @duel.id}), :method => :post, remote: true, class: "bookmark_link" do %>
				<%= image_tag "/assets/love.png", class: "bookmark" %>
			<% end %>
		<% end %>	
	<% end %>
</div>

momichetabg/app/views/battles/_form.html.erb
<%= form_for(@battle) do |f| %>
  <% if @battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% @battle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :oponent1_id %><br>
    <%= f.number_field :oponent1_id %>
  </div>
  <div class="field">
    <%= f.label :oponent2_id %><br>
    <%= f.number_field :oponent2_id %>
  </div>
  <div class="field">
    <%= f.label :oponent1_votes %><br>
    <%= f.number_field :oponent1_votes %>
  </div>
  <div class="field">
    <%= f.label :oponent2_votes %><br>
    <%= f.number_field :oponent2_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

momichetabg/app/views/battles/admin.html.erb
<div class="container">
	<h2> Total number of images: <%= @total_images %> </h2>
	<h2> <%= @total_images/2 %> Couples</h2>
	<h2> Number of ready images: <%= @number_of_ready_images %> </h2>
	<%= button_to "Start Battles", start_tournament_path %>
	<%= button_to "Move Battles", move_tournament_path %>
</div>

momichetabg/app/views/battles/battle.js.erb
var parent = $('#battle').parent();
$('#battle').remove();
parent.prepend("<%=j render 'battle' %>");

momichetabg/app/views/battles/bookmark.js.erb
var parent = $('#bookmark').parent();
$('#bookmark').remove();
parent.prepend("<%=j render 'bookmark' %>");

momichetabg/app/views/battles/edit.html.erb
<h1>Editing battle</h1>

<%= render 'form' %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>

momichetabg/app/views/battles/index.html.erb
<div id="fb-root"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) 
            return;
        js = d.createElement(s); 
        js.id = id;
        js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }
    (document, 'script', 'facebook-jssdk'));
</script>

<% unless @duel.nil? %>
    <div class="container">
        <h2 class="heading">Всеки има право да гласува по веднъж на ден.</h2>

        <div class="pull-right"><div class="fb-like" data-href="https://www.facebook.com/pages/%D0%9C%D0%BE%D0%BC%D0%B8%D1%87%D0%B5%D1%82%D0%B0%D0%91%D0%B3/425395310930108?ref=hl" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div></div>
        <p class='desc'><strong>Кликни върху снимката</strong> на твоята фоворитка, за да гласуваш!</br><em>(Втори кръг от 11-ти март до 22:00 часа на 17-ти март)</em></p>
        <!-- the like button -->
        <div>
            <%= render 'battle' %>
        </div>
        <div class="shadow"></div>
        <div class="text-center">
            <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fparse.com" class="fb-share btn btn-primary  btn-lg "><i class="glyphicon glyphicon-thumbs-up icon-white"></i>Сподели в Facebook</a>
        </div>
    </div><!-- /container -->
<% else %>
    <h2>Няма активни битки в този момент...</h2>
<% end %>

momichetabg/app/views/battles/new.html.erb
<h1>New battle</h1>

<%= render 'form' %>

<%= link_to 'Back', battles_path %>

momichetabg/app/views/battles/picture_history.html.erb
<div class="container">
	<% if not @battles.nil? %>
		<% @battles.each do |b| %>
			<% @duel = b %>
			<div>
				<%= render 'battle_nojs' %>
			</div>
		<% end %>
	<% end %>
</div>

momichetabg/app/views/battles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oponent1:</strong>
  <%= @battle.oponent1_id %>
</p>

<p>
  <strong>Oponent2:</strong>
  <%= @battle.oponent2_id %>
</p>

<p>
  <strong>Oponent1 votes:</strong>
  <%= @battle.oponent1_votes %>
</p>

<p>
  <strong>Oponent2 votes:</strong>
  <%= @battle.oponent2_votes %>
</p>

<%= link_to 'Edit', edit_battle_path(@battle) %> |
<%= link_to 'Back', battles_path %>

momichetabg/app/views/battles/subscriptions.html.erb
<div class="container">
	<% if not @sub.nil? %>
		<% @sub.each do |s| %>
			<% @duel = Battle.find(s.battle_id)
				 if @duel.nil?
				 	@choice = BattleVote.where(battle_id: @duel.id).where(user_id: current_user.id).first.choice
				 else 
				 	@choice = 0
				 end
			%>
			<div>
				<%= render 'battle_nojs' %>
			</div>
		<% end %>
	<% end %>
</div>